resources:
  limits:
    cpus: 2.0
    memory: 4096

kometa:
  plex_url: http://192.168.1.100:32400
  plex_token: token
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 8080

run_as:
  user: 501 # todo: revert to 568
  group: 20 # todo: revert to 568

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
